//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmOrder_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfirmOrder_()
        {
            this.Payment_ = new HashSet<Payment_>();
        }
    
        public double CfOrderId_ { get; set; }
        public Nullable<double> OrderId_ { get; set; }
        public string CfOrderMenu_ { get; set; }
        public string CfOrderTime_ { get; set; }
    
        public virtual Order_ Order_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_> Payment_ { get; set; }
    }
}
