//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_()
        {
            this.Material_ = new HashSet<Material_>();
            this.Menu_ = new HashSet<Menu_>();
        }
    
        public double EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpLName { get; set; }
        public int EmpPoId { get; set; }
        public string EmpTel { get; set; }
        public Nullable<double> EmpHnum { get; set; }
        public Nullable<double> EmpSoi { get; set; }
        public string EmpMoo { get; set; }
        public string EmpRoad { get; set; }
        public string SareaName { get; set; }
        public string DareaName { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<double> EmpPostal { get; set; }
        public Nullable<double> EmpPassword { get; set; }
    
        public virtual EmpPosition_ EmpPosition_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_> Material_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_> Menu_ { get; set; }
    }
}
