//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPosition_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpPosition_()
        {
            this.Employee_ = new HashSet<Employee_>();
        }
    
        public int EmpPoId { get; set; }
        public string EmpPosition { get; set; }
        public Nullable<int> EmpSalary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_> Employee_ { get; set; }
    }
}
