//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_
    {
        public double ExId_ { get; set; }
        public double ROrderId_ { get; set; }
        public string ExName { get; set; }
        public string ExLName { get; set; }
    
        public virtual ReceiptOrder_ ReceiptOrder_ { get; set; }
    }
}
