//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_()
        {
            this.Quotation_ = new HashSet<Quotation_>();
        }
    
        public double MatId_ { get; set; }
        public double EmpId_ { get; set; }
        public Nullable<System.DateTime> MatDate_ { get; set; }
        public string MatList_ { get; set; }
        public string MatUnit { get; set; }
        public Nullable<double> MatPrice_ { get; set; }
    
        public virtual Employee_ Employee_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation_> Quotation_ { get; set; }
    }
}
