//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_()
        {
            this.Order_ = new HashSet<Order_>();
        }
    
        public double MenuId_ { get; set; }
        public Nullable<double> TMenuId_ { get; set; }
        public Nullable<double> EmpId_ { get; set; }
        public string MenuName_ { get; set; }
        public Nullable<double> MenuPrice_ { get; set; }
    
        public virtual Employee_ Employee_ { get; set; }
        public virtual TypeMenu_ TypeMenu_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_> Order_ { get; set; }
    }
}
