//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_()
        {
            this.ConfirmOrder_ = new HashSet<ConfirmOrder_>();
        }
    
        public double OrderId { get; set; }
        public Nullable<double> MenuId_ { get; set; }
        public Nullable<double> OrderUnit_ { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderTime_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmOrder_> ConfirmOrder_ { get; set; }
        public virtual Menu_ Menu_ { get; set; }
    }
}
