//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder_()
        {
            this.ReceiptOrder_ = new HashSet<ReceiptOrder_>();
        }
    
        public double POrderId_ { get; set; }
        public Nullable<double> QuoId_ { get; set; }
        public string POrderName_ { get; set; }
        public string POrderLName_ { get; set; }
        public Nullable<System.DateTime> POrderDate_ { get; set; }
    
        public virtual Quotation_ Quotation_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptOrder_> ReceiptOrder_ { get; set; }
    }
}
