//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation_()
        {
            this.PurchaseOrder_ = new HashSet<PurchaseOrder_>();
        }
    
        public double QuoId { get; set; }
        public Nullable<double> MatId_ { get; set; }
        public string QuoName_ { get; set; }
        public string QuoLName_ { get; set; }
        public Nullable<double> QuoTel_ { get; set; }
        public string QuoShopName_ { get; set; }
        public string QuoHnum_ { get; set; }
        public Nullable<double> QuoSoi_ { get; set; }
        public string QuoMoo_ { get; set; }
        public string QuoRoad_ { get; set; }
        public string SareaId { get; set; }
        public string DareaId { get; set; }
        public string ProvinceId { get; set; }
        public Nullable<double> QuoPostal_ { get; set; }
    
        public virtual Material_ Material_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder_> PurchaseOrder_ { get; set; }
    }
}
