//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt_()
        {
            this.Revenue_ = new HashSet<Revenue_>();
        }
    
        public double RecId_ { get; set; }
        public Nullable<double> PayId_ { get; set; }
        public Nullable<System.DateTime> RecDate_ { get; set; }
        public string RecName_ { get; set; }
        public string RecLName_ { get; set; }
        public string RecTime_ { get; set; }
        public Nullable<double> RecAmount_ { get; set; }
    
        public virtual Payment_ Payment_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue_> Revenue_ { get; set; }
    }
}
