//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptOrder_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptOrder_()
        {
            this.Expenses_ = new HashSet<Expenses_>();
        }
    
        public double ROrderId_ { get; set; }
        public Nullable<double> POrderId_ { get; set; }
        public string ROrderName_ { get; set; }
        public string ROrderLName_ { get; set; }
        public Nullable<System.DateTime> RorderDate_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenses_> Expenses_ { get; set; }
        public virtual PurchaseOrder_ PurchaseOrder_ { get; set; }
    }
}
