//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veryVerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue_
    {
        public double RevId_ { get; set; }
        public Nullable<double> RecId_ { get; set; }
        public string RevName_ { get; set; }
        public string RevLName_ { get; set; }
    
        public virtual Receipt_ Receipt_ { get; set; }
    }
}
